### ISSUE TITLE
When I clone this repo `darkBlue` shows up as modified

### ISSUE THREAD

**Issue by jsatk** [flazz/vim-colorschemes#152]
If I do a fresh `git clone git@github.com:flazz/vim-colorschemes.git && cd vim-colorschemes && git status` it shows me this.

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   colors/darkBlue.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

I've tried the following with no success: 
* `git checkout -- colors/darkBlue.vim`
* `git stash && git fetch origin && git reset --hard origin/master`
* `git mv colors/darkBlue.vim colors/darkblue.vim`

All fail.

Any idea why this is? It's borking my plugin manager every time I update.

**Comment by jsatk** [comment]
This issue relates to or duplicates issues raised in https://github.com/flazz/vim-colorschemes/issues/66 & https://github.com/flazz/vim-colorschemes/issues/122.

**Comment by andreis** [comment]
Same here. Somehow the case change (`colors/darkBlue.vim` -> `colors/darkblue.vim`) messed something up. 🙄

**Comment by bradwood** [comment]
Same with me -- it's super annoying as the repo remains dirty:

```
 ~/Code/Dotfiles/config/nvim/plugged  ✔  git clone  https://github.com/flazz/vim-colorschemes.git
Cloning into 'vim-colorschemes'...
remote: Enumerating objects: 1769, done.
remote: Total 1769 (delta 0), reused 0 (delta 0), pack-reused 1769
Receiving objects: 100% (1769/1769), 1.88 MiB | 2.85 MiB/s, done.
Resolving deltas: 100% (579/579), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'colors/darkBlue.vim'
  'colors/darkblue.vim'
 ~/Code/Dotfiles/config/nvim/plugged  ✔ 
```

this might shed some light...

Someone with commit rights (@flazz ??) should be able to fix it easily?  Will see if I can do a PR in the mean time.

**Comment by jsatk** [comment]
I think they've abandoned it?

**Comment by jsatk** [comment]
This is clearly abandoned.
