### ISSUE TITLE
Tomorrow-Night was improperly updated

### ISSUE THREAD

**Issue by ichitera** [flazz/vim-colorschemes#157]
After 90b25265feab2f51cd6d821a3b6b173df7759730, many colors of Tomorrow-Night were changed. The colors seem not to be included in [the original Tomorrow-Night palette](https://github.com/chriskempson/tomorrow-theme), so I thought that 90b25265feab2f51cd6d821a3b6b173df7759730 improperly updated Tomorro-Night.

**before 90b25265feab2f51cd6d821a3b6b173df7759730:**
![old](https://user-images.githubusercontent.com/31098747/48811429-0c678b80-ed71-11e8-8cd8-7e6bcd64b5f2.png)

**after 90b25265feab2f51cd6d821a3b6b173df7759730:**
![new](https://user-images.githubusercontent.com/31098747/48811491-58b2cb80-ed71-11e8-903b-e2661ef1f2a8.png)

NOTE:
- the source code in the above images is from [vimcolors.com](http://vimcolors.com/53/Tomorrow-Night/dark)

**Comment by jhawksley** [comment]
I'm also having trouble with this theme using Plugged/nvim.  May be unrelated, but anyway:

`
Error detected while processing /<me>/.config/nvim/plugged/vim-colorschemes/colors/Tomorrow-Night.vim:
line   44:
E122: Function <SNR>16_grey_number already exists, add ! to replace it
line   53:
E122: Function <SNR>16_grey_level already exists, add ! to replace it
line   64:
E122: Function <SNR>16_grey_colour already exists, add ! to replace it
line   79:
E122: Function <SNR>16_rgb_number already exists, add ! to replace it
line   88:
E122: Function <SNR>16_rgb_level already exists, add ! to replace it
line   93:
E122: Function <SNR>16_rgb_colour already exists, add ! to replace it
line  129:
E122: Function <SNR>16_colour already exists, add ! to replace it
line  139:
E122: Function <SNR>16_rgb already exists, add ! to replace it
`

**Comment by gfontenot** [comment]
Lucius was improperly updated as well. The update changed a bunch of the colors, and removed the helper functions for setting the color variants. Any chance of reverting that commit?

**Comment by taylorthurlow** [comment]
Also having the same issue with `Tomorrow-Night`.

**Comment by thejohnfreeman** [comment]
@flazz or @ichitera , you can mark this closed now.

**Comment by gfontenot** [comment]
This is fixed for Tomorrow Night, but the same change broke countless other themes. Tomorrow Night is just the most visible one that broke. The correct change to fix this issue is almost certainly to revert 90b25265feab2f51cd6d821a3b6b173df7759730

**Comment by tbodt** [comment]
If your current colorscheme broke as a result of that commit I would recommend installing it from its original source, that way it won't break and it can be updated by the creator.

**Comment by ichitera** [comment]
@thejohnfreeman, thank you for the notification. I confirmed that Tomorrow-Night was back to the original. Also, @tbdt, thank you for the pull-request.

Although @gfontenot reported that other themese also were broken, I will close this issue because this issue mentioned only Tomorrow-Night, and this colorscheme was fixed.

@gfontenot or someone, please create a new issue if you find other broken colorschemes. I did not check the other colorschemes, and I did not encounter other broken colorschemes.
