### ISSUE TITLE
Sorting color schemes by color support

### ISSUE THREAD

**Issue by devhell** [flazz/vim-colorschemes#16]
Hi,

Any chance you could sort the color schemes by color support?
For example, put all the 256-color schemes in one directory, and the 16-color schemes in another directory?

It would help people who have different terminals with different levels of color support to quickly find which themes they can apply.

Thanks!

**Comment by flazz** [comment]
Can you give an example how we could sort these? I'm not sure this is as easy as it seems, not all colorschemes fully support 16 color or 256 color.

But to come close I think some a simple shell script could detect which ones has different levels of support. I'm winging it, but detecting `gui` or `cterm` might be a good starting point. Let me know what you come up with, maybe this could end up as a vim command called Colorscheme16 or Colorscheme256.
