### ISSUE TITLE
3 problematic color schems

### ISSUE THREAD

**Issue by ndzou** [flazz/vim-colorschemes#24]
This is the ultimate collection of color schemes.  The selection can probably satisfy almost anyone.   However, I feel that regardless of the aesthetic appeal of a particular color scheme, it should not have unexpected side effects.  For example, changing the user's editor window size, font, messing with the editing buffer, etc.  3 color schemes failed the above test:

1) darkroom: messes up the current editing buffer by creating a new scratch buffer
2) potts: tries to set the font to 7x13 (very ugly font)
3) smyck: tries to change the linespace to 2 (many people prefer a tighter line space)

There're other color schemes that also have issues, like scala and ciscoacl, after using these schemes certain colors are stuck, that even if you change to another color scheme they won't get restored.  But I feel at a minimum the editor content/window size should not change.

If you agree that these are issues that should be addressed, I can send a pull request with the changes.

**Comment by flazz** [comment]
If we can get those changes in upstream I'm all for it. Otherwise can you make derivatives that solve your issues. Eg. darkroom-sans-bullshit.vim or whatever 😄

**Comment by KubaKaszycki** [comment]
The 7x13 font means that the theme sets a font, but it cannot be found. Please get some files that were distributed together with original potts.

Also, the 2nd and 3rd issues affect **only** GVim.
