### ISSUE TITLE
Conceal rules missing in a bunch of colorschemes

### ISSUE THREAD

**Issue by fmoralesc** [flazz/vim-colorschemes#27]
[At vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax/issues/32), we've found that many colorschemes don't have explicit rules for the Conceal group, which creates this sort of issue (see the grey background in the first half of the text):

<img src="https://f.cloud.github.com/assets/2703310/1916677/40d5ebf4-7d7e-11e3-8cfd-7546030b444f.png" />

Checking on the contents of this repo, only a few colorschemes provide correct rules for Conceal: https://github.com/flazz/vim-colorschemes/search?q=Conceal&source=cc

I'm not sure this is the right place to raise this issue, but I thought it would be good to let you know.

We've found adding

   hi link Conceal Operator

to the colorschemes works fine in our use-case, but a different rule might be needed in others.

**Comment by flazz** [comment]
PR?
