### ISSUE TITLE
Update vividchalk from tpope/vividchalk

### ISSUE THREAD

**Issue by RhysU** [flazz/vim-colorschemes#31]
Please consider updating vividchalk from https://github.com/tpope/vim-vividchalk/blob/master/colors/vividchalk.vim.  There are some minor changes related to CursorColumn that greatly improve its experience.

**Comment by flazz** [comment]
PR?

**Comment by flazz** [comment]
also I don't like to break existing users so the PR would have to be upstream aligned, otherwise please call it something else, but please respect the license of the original work.
