### ISSUE TITLE
Please define releases for vim-colorschemes

### ISSUE THREAD

**Issue by tim-lebedkov** [flazz/vim-colorschemes#50]
It would be nice if you could define releases. It is unclear what is stable and what is not.

**Comment by flazz** [comment]
I agree with @zachgersh each git revision is a release :), There is no abi or api compatibilities that a version helps solve … just a bunch of themes. 

But to your immediate issue, I can think of a few options:

what if you versioned your packages on time based snapshots: 15.8 -> October 15, 2015, etc. kinda like how ubuntu does it? possibly with an extension like `15.8-gf1ade59eff` where the g ties it to the commit?

Alternatively you could count the number of commits from the first one and use that? This might be more aligned with "when big things change".
