### ISSUE TITLE
vim-colourscheme - git update server info on the server?

### ISSUE THREAD

**Issue by aodock** [flazz/vim-colorschemes#58]
Hi, im new to Vim / vim plugins / and also github.
so far i have installed few plugins through vundle and now I am trying to install flazz/vim-colorschemes.
when i run `:PluginInstall`, it asks me github username and password. After providing the password i get something as follows
`fatal: https://github.com/flazz/vim-colourschemes.git/info/refs?service=git-upload-pack not found: did you run git update-server-info on the server?`

![vim colours](https://cloud.githubusercontent.com/assets/9947746/5196411/fa659122-7554-11e4-922c-72eb9c4a39b1.png)

need help plz.

**Comment by flazz** [comment]
you might need to setup .netrc with a github api key. https://gist.github.com/technoweenie/1072829, or google a bit for `netrc github`

**Comment by aodock** [comment]
@flazz..  thanks
