### ISSUE TITLE
Fix typo in Monokai than makes unusable this colorscheme

### ISSUE THREAD

**Issue by liloman** [flazz/vim-colorschemes#62]
<pre><code>
diff --git a/colors/Monokai.vim b/colors/Monokai.vim
index fa31009..570625e 100644
--- a/colors/Monokai.vim
+++ b/colors/Monokai.vim
@@ -9,7 +9,7 @@ if exists("syntax_on")
 endif
 
 set t_Co=256
-let g:colors_name = "monokai"
+let g:colors_name = "Monokai"
 
 hi Cursor ctermfg=235 ctermbg=231 cterm=NONE guifg=#272822 guibg=#f8f8f0 gui=NONE
 hi Visual ctermfg=NONE ctermbg=59 cterm=NONE guifg=NONE guibg=#49483e gui=NONE
-- 
2.1.0
</code></pre>

**Comment by flazz** [comment]
how does the patch align with upstream monokai?

**Comment by liloman** [comment]
diff --git a/colors/Monokai.vim b/colors/Monokai.vim
index fa31009..570625e 100644
--- a/colors/Monokai.vim
+++ b/colors/Monokai.vim
@@ -9,7 +9,7 @@ if exists("syntax_on")
 endif
 
 set t_Co=256
-let g:colors_name = "monokai"
+let g:colors_name = "Monokai"
 
 hi Cursor ctermfg=235 ctermbg=231 cterm=NONE guifg=#272822 guibg=#f8f8f0 gui=NONE
 hi Visual ctermfg=NONE ctermbg=59 cterm=NONE guifg=NONE guibg=#49483e gui=NONE


====
Updated to upstream. 

Sorry for the delay but It's been a long time without a proper DSL.

Awesome job. :) 

Cheers

**Comment by flazz** [comment]
can you do this in a PR?

**Comment by liloman** [comment]
Done [pull 95](https://github.com/flazz/vim-colorschemes/pull/95)
