### ISSUE TITLE
Request: Add Afterglow theme

### ISSUE THREAD

**Issue by nick-s-b** [flazz/vim-colorschemes#65]
There's a really nice looking theme for Sublime called [afterglow](https://github.com/YabataDesign/afterglow-theme). Does anyone have the time & knows how to convert it to vim? I'd like to see it in vim-colorschemes. Thanks in advance!

**Comment by flazz** [comment]
I don't have time, but there are a handful of color theme tools that support vim, maybe you can import the sublime and get vim out?

**Comment by flazz** [comment]
PR is graciously accepted whenever!
