### ISSUE TITLE
E185: Cannot find color scheme .. any scheme

### ISSUE THREAD

**Issue by ltarasiewicz** [flazz/vim-colorschemes#87]
Hello,

I've installed vim-colorschemes with Vundle. All color schemes are dropped into `.vim/bundle/vim-colorschemes/colors`.

When I drop `colorscheme corn` or any other colorscheme, I always get en error:

>> E185: Cannot find color scheme ...

Is that a bug or am I doing something wrong?

**Comment by PaulDapolito** [comment]
+1

Seems like the `colors` folder is installed to ~/.vim/bundle/vim-colorschemes/colors by default. You can fix this by running `cp -r ~/.vim/bundle/vim-colorschemes/colors ~/.vim/colors`.

**Comment by dragonxlwang** [comment]
it's probably because you put colorscheme before vundle call ends. Put it outside plugin loading and it should be fine... ask me how i know it in the hard way...

**Comment by libuk** [comment]
@dragonxlwang This fixed it for me.
